### ISSUE TITLE
What does minimal navigation mean?

### ISSUE THREAD

**Issue by BoyanP** [CMPUT301W15T01/Team1Project#15]
What does minimal navigation mean?

**Comment by Joduro** [comment]
Answer: 
"It means make it usable and not difficult.
A test for this could be an acceptance test that is executed manually and ensure that within 2-4 button presses we can enter an expense item. Realisticly you could do it in 2:
* click modify current expense in the launcher
* click add expense item
Or:
* click on app in launcher
* click on current expense
* click add expense item
You can test this (the navigable steps are less than or equal to 4) or you can manually test it."

For this to work we might need to get rid of the login screen and the dialogues to edit/delete.
Right now if my understanding is correct we have:
1. click on app in launcher
2. click user at start screen
3. click claim
4. long click expense
5. click edit in dialogue 

My thoughts:
- We could replace the login screen with being able to switch between claimant and approver by opening the menu on the claimslist screen
- We could have just clicking an expense also lead to the edit expense screen
Then the process could be:
1. click on app in launcher
2. click claim
3. click expense 

So either one of those changes could make it the required 4 clicks instead of 5.

**Comment by Cdingram** [comment]
Ya those are good ideas, we'll have to think about refining the UI
