### ISSUE TITLE
We have two different claim list test files

### ISSUE THREAD

**Issue by Cdingram** [CMPUT301W15T01/Team1Project#79]

**Comment by aylmao** [comment]
no claims test file for claimant and one for approver

**Comment by aylmao** [comment]
some how "main activity.java" has been renamed, so I changed it on the files to the new name ClaimantClaimsListActivity

**Comment by yotomyoto** [comment]
I changed that names of two files because I realized the one I was working on should have been the ClaimantClaimsListTest.java and the one that was called that was actually just testing Claims not the ClaimsList hence I renamed it ClaimTest. Sorry for the confusion if this is what you're refering to.
